INSERT INTO tb_client(name, phone_number, address) VALUES('James', '(99) 98723-3281', 'Bairro Jardim, Rua 22 - 3131'      );
INSERT INTO tb_client(name, phone_number, address) VALUES('Anny', '(99) 98644-7553', 'Bairro Aurora, Rua 24 - 6414'      );
INSERT INTO tb_client(name, phone_number, address) VALUES('Lucia', '(98) 99457-9145', 'Bairro Bela Noite, Rua 9 - 3131'  );
INSERT INTO tb_client(name, phone_number, address) VALUES('Apollo', '(34) 98644-7553', 'Bairro Seraphim, Rua 4 - 1754'   );
INSERT INTO tb_client(name, phone_number, address) VALUES('Nadia', '(23) 95788-1534', 'Bairro Bela Noite, Rua 8 - 3119'  );
INSERT INTO tb_client(name, phone_number, address) VALUES('Anton', '(67) 96764-2463', 'Bairro Seraphim, Rua 2 - 1736'    );
INSERT INTO tb_client(name, phone_number, address) VALUES('Helena', '(99) 99507-8355', 'Bairro Novo Norte, Rua 45 - 7154');
INSERT INTO tb_client(name, phone_number, address) VALUES('Wallace', '(99) 93002-6043', 'Bairro Aurora, Rua 30 - 6894'   );
INSERT INTO tb_client(name, phone_number, address) VALUES('Micael', '(99) 98323-3431', 'Bairro Jardim, Rua 21 - 3133');
INSERT INTO tb_client(name, phone_number, address) VALUES('Lianna', '(58) 98865-6443', 'Bairro Aurora, Rua 26 - 6416');
INSERT INTO tb_client(name, phone_number, address) VALUES('Isabella', '(58) 99457-9145', 'Bairro Bela Noite, Rua 9 - 2341');
INSERT INTO tb_client(name, phone_number, address) VALUES('Alberto', '(66) 98673-3745', 'Bairro Seraphim, Rua 3 - 1754');
INSERT INTO tb_client(name, phone_number, address) VALUES('Paulo', '(66) 97008-1534', 'Bairro Bela Noite, Rua 9 - 3117');
INSERT INTO tb_client(name, phone_number, address) VALUES('Vitor', '(72) 96464-2523', 'Bairro Seraphim, Rua 2 - 1739');
INSERT INTO tb_client(name, phone_number, address) VALUES('Julia', '(72) 99037-8695', 'Bairro Novo Norte, Rua 45 - 7154');
INSERT INTO tb_client(name, phone_number, address) VALUES('Gabriel', '(99) 93692-6432', 'Bairro Aurora, Rua 30 - 6899');
INSERT INTO tb_client(name, phone_number, address) VALUES('Maria', '(99) 98123-4567', 'Bairro Recanto do Sul, Rua 1 - 1283');
INSERT INTO tb_client(name, phone_number, address) VALUES('João', '(98) 98234-5678', 'Bairro Lua Nova, Rua 2 - 2334');
INSERT INTO tb_client(name, phone_number, address) VALUES('Ana', '(63) 98345-6789', 'Bairro Estrela Azul, Rua 3 - 3455');
INSERT INTO tb_client(name, phone_number, address) VALUES('Pedro', '(74) 98456-7890', 'Bairro Recanto do Sul, Rua 4 - 4536');
INSERT INTO tb_client(name, phone_number, address) VALUES('Mariana', '(32) 98567-8901', 'Bairro Lua Nova, Rua 5 - 5867');
INSERT INTO tb_client(name, phone_number, address) VALUES('Carlos', '(23) 98678-9012', 'Bairro Estrela Azul, Rua 6 - 6578');
INSERT INTO tb_client(name, phone_number, address) VALUES('Fernanda', '(64) 98789-0123', 'Bairro Recanto do Sul, Rua 7 - 7589');
INSERT INTO tb_client(name, phone_number, address) VALUES('Ricardo', '(99) 98890-1234', 'Bairro Lua Nova, Rua 8 - 8970');
INSERT INTO tb_client(name, phone_number, address) VALUES('Juliana', '(99) 98901-2345', 'Bairro Estrela Azul, Rua 9 - 9081');
INSERT INTO tb_client(name, phone_number, address) VALUES('Paulo', '(46) 98012-3456', 'Bairro Recanto do Sul, Rua 10 - 0132');
INSERT INTO tb_client(name, phone_number, address) VALUES('Luiza', '(63) 98111-2233', 'Bairro Primavera, Rua 11 - 4342');
INSERT INTO tb_client(name, phone_number, address) VALUES('Rafael', '(53) 98222-3344', 'Bairro Cachoeira, Rua 12 - 5433');
INSERT INTO tb_client(name, phone_number, address) VALUES('Camila', '(99) 98333-4455', 'Bairro Primavera, Rua 13 - 6544');
INSERT INTO tb_client(name, phone_number, address) VALUES('André', '(99) 98444-5566', 'Bairro Cachoeira, Rua 14 - 7665');

INSERT INTO tb_client_account(client_id, debt_quantity, debt_amount, paid_quantity, paid_amount) VALUES(1, 0, 0.0, 0, 0.0);
INSERT INTO tb_client_account(client_id, debt_quantity, debt_amount, paid_quantity, paid_amount) VALUES(2, 0, 0.0, 0, 0.0);
INSERT INTO tb_client_account(client_id, debt_quantity, debt_amount, paid_quantity, paid_amount) VALUES(3, 0, 0.0, 0, 0.0);
INSERT INTO tb_client_account(client_id, debt_quantity, debt_amount, paid_quantity, paid_amount) VALUES(4, 0, 0.0, 0, 0.0);
INSERT INTO tb_client_account(client_id, debt_quantity, debt_amount, paid_quantity, paid_amount) VALUES(5, 0, 0.0, 0, 0.0);
INSERT INTO tb_client_account(client_id, debt_quantity, debt_amount, paid_quantity, paid_amount) VALUES(6, 0, 0.0, 0, 0.0);
INSERT INTO tb_client_account(client_id, debt_quantity, debt_amount, paid_quantity, paid_amount) VALUES(7, 0, 0.0, 0, 0.0);
INSERT INTO tb_client_account(client_id, debt_quantity, debt_amount, paid_quantity, paid_amount) VALUES(8, 0, 0.0, 0, 0.0);
INSERT INTO tb_client_account(client_id, debt_quantity, debt_amount, paid_quantity, paid_amount) VALUES(9, 0, 0.0, 0, 0.0);
INSERT INTO tb_client_account(client_id, debt_quantity, debt_amount, paid_quantity, paid_amount) VALUES(10, 0, 0.0, 0, 0.0);
INSERT INTO tb_client_account(client_id, debt_quantity, debt_amount, paid_quantity, paid_amount) VALUES(11, 0, 0.0, 0, 0.0);
INSERT INTO tb_client_account(client_id, debt_quantity, debt_amount, paid_quantity, paid_amount) VALUES(12, 0, 0.0, 0, 0.0);
INSERT INTO tb_client_account(client_id, debt_quantity, debt_amount, paid_quantity, paid_amount) VALUES(13, 0, 0.0, 0, 0.0);
INSERT INTO tb_client_account(client_id, debt_quantity, debt_amount, paid_quantity, paid_amount) VALUES(14, 0, 0.0, 0, 0.0);
INSERT INTO tb_client_account(client_id, debt_quantity, debt_amount, paid_quantity, paid_amount) VALUES(15, 0, 0.0, 0, 0.0);
INSERT INTO tb_client_account(client_id, debt_quantity, debt_amount, paid_quantity, paid_amount) VALUES(16, 0, 0.0, 0, 0.0);
INSERT INTO tb_client_account(client_id, debt_quantity, debt_amount, paid_quantity, paid_amount) VALUES(17, 0, 0.0, 0, 0.0);
INSERT INTO tb_client_account(client_id, debt_quantity, debt_amount, paid_quantity, paid_amount) VALUES(18, 0, 0.0, 0, 0.0);
INSERT INTO tb_client_account(client_id, debt_quantity, debt_amount, paid_quantity, paid_amount) VALUES(19, 0, 0.0, 0, 0.0);
INSERT INTO tb_client_account(client_id, debt_quantity, debt_amount, paid_quantity, paid_amount) VALUES(20, 0, 0.0, 0, 0.0);
INSERT INTO tb_client_account(client_id, debt_quantity, debt_amount, paid_quantity, paid_amount) VALUES(21, 0, 0.0, 0, 0.0);
INSERT INTO tb_client_account(client_id, debt_quantity, debt_amount, paid_quantity, paid_amount) VALUES(22, 0, 0.0, 0, 0.0);
INSERT INTO tb_client_account(client_id, debt_quantity, debt_amount, paid_quantity, paid_amount) VALUES(23, 0, 0.0, 0, 0.0);
INSERT INTO tb_client_account(client_id, debt_quantity, debt_amount, paid_quantity, paid_amount) VALUES(24, 0, 0.0, 0, 0.0);
INSERT INTO tb_client_account(client_id, debt_quantity, debt_amount, paid_quantity, paid_amount) VALUES(25, 0, 0.0, 0, 0.0);
INSERT INTO tb_client_account(client_id, debt_quantity, debt_amount, paid_quantity, paid_amount) VALUES(26, 0, 0.0, 0, 0.0);
INSERT INTO tb_client_account(client_id, debt_quantity, debt_amount, paid_quantity, paid_amount) VALUES(27, 0, 0.0, 0, 0.0);
INSERT INTO tb_client_account(client_id, debt_quantity, debt_amount, paid_quantity, paid_amount) VALUES(28, 0, 0.0, 0, 0.0);
INSERT INTO tb_client_account(client_id, debt_quantity, debt_amount, paid_quantity, paid_amount) VALUES(29, 0, 0.0, 0, 0.0);
INSERT INTO tb_client_account(client_id, debt_quantity, debt_amount, paid_quantity, paid_amount) VALUES(30, 0, 0.0, 0, 0.0);


INSERT INTO tb_product (description, price) VALUES ('Chocolate Amargo 200g', 3.80);
INSERT INTO tb_product (description, price) VALUES ('Refrigerante Fanta Laranja Mini Pet 250ml', 1.75);
INSERT INTO tb_product (description, price) VALUES ('Refrigerante Fanta Uva Mini Pet 250ml', 1.75);
INSERT INTO tb_product (description, price) VALUES ('Refrigerante Kuat Mini Pet 250ml', 1.75);
INSERT INTO tb_product (description, price) VALUES ('Linguíça Toscana P/Churrasco Friato Pacote 5kg', 21.90);
INSERT INTO tb_product (description, price) VALUES ('Iorgute Activia Líquido Prc Ameixa Danone 150g', 2.95);
INSERT INTO tb_product (description, price) VALUES ('Iorgute Activia Líquido Prc Morango Danone 150g', 2.95);
INSERT INTO tb_product (description, price) VALUES ('Arroz Carvalho 5kg', 23.50);
INSERT INTO tb_product (description, price) VALUES ('Leite Piracanjuba Desnatado Líquido 1l', 9.90);
INSERT INTO tb_product (description, price) VALUES ('Café Santa Clara 250g', 9.90);
INSERT INTO tb_product (description, price) VALUES ('Óleo de Milho Sinhá 1l', 3.30);
INSERT INTO tb_product (description, price) VALUES ('Feijâo Preto Mayara 1kg', 9.80);
INSERT INTO tb_product (description, price) VALUES ('Sal Cavalinho 1kg', 1.0);
INSERT INTO tb_product (description, price) VALUES ('Chocolate ao Leite 100g', 5.50);
INSERT INTO tb_product (description, price) VALUES ('Água Mineral 500ml', 1.00);
INSERT INTO tb_product (description, price) VALUES ('Cerveja Lata 350ml', 4.25);
INSERT INTO tb_product (description, price) VALUES ('Salgadinho de Queijo 45g', 3.00);
INSERT INTO tb_product (description, price) VALUES ('Pão de Forma Integral 500g', 6.00);
INSERT INTO tb_product (description, price) VALUES ('Iogurte Natural 170g', 2.75);
INSERT INTO tb_product (description, price) VALUES ('Café Solúvel 50g', 8.20);
INSERT INTO tb_product (description, price) VALUES ('Refrigerante Coca-Cola Lata 350ml', 3.50);
INSERT INTO tb_product (description, price) VALUES ('Biscoito Recheado 140g', 2.90);
INSERT INTO tb_product (description, price) VALUES ('Arroz Branco 1kg', 4.00);
INSERT INTO tb_product (description, price) VALUES ('Feijão Preto 1kg', 5.50);
INSERT INTO tb_product (description, price) VALUES ('Molho de Tomate 340g', 3.00);


INSERT INTO tb_debt(client_id, debt_date, product_quantity, product_amount,  product_id) VALUES(1, '2024-01-12', 4, 0.0, 1);
INSERT INTO tb_debt(client_id, debt_date, product_quantity, product_amount,  product_id) VALUES(1, '2024-01-12', 2, 0.0, 4);
INSERT INTO tb_debt(client_id, debt_date, product_quantity, product_amount,  product_id) VALUES(1, '2024-01-05', 1, 0.0, 9);
INSERT INTO tb_debt(client_id, debt_date, product_quantity, product_amount,  product_id) VALUES(6, '2024-01-05', 1, 0.0, 1);
INSERT INTO tb_debt(client_id, debt_date, product_quantity, product_amount,  product_id) VALUES(2, '2024-01-10', 8, 0.0, 5);
INSERT INTO tb_debt(client_id, debt_date, product_quantity, product_amount,  product_id) VALUES(3, '2024-01-05', 5, 0.0, 3);
INSERT INTO tb_debt(client_id, debt_date, product_quantity, product_amount,  product_id) VALUES(2, '2024-01-20', 2, 0.0, 6);
INSERT INTO tb_debt(client_id, debt_date, product_quantity, product_amount,  product_id) VALUES(6, '2024-02-02', 3, 0.0, 11);
INSERT INTO tb_debt(client_id, debt_date, product_quantity, product_amount,  product_id) VALUES(5, '2024-02-05', 2, 0.0, 7);
INSERT INTO tb_debt(client_id, debt_date, product_quantity, product_amount,  product_id) VALUES(7, '2024-02-13', 9, 0.0, 2);
INSERT INTO tb_debt(client_id, debt_date, product_quantity, product_amount,  product_id) VALUES(4, '2024-02-16', 14, 0.0, 8);
INSERT INTO tb_debt(client_id, debt_date, product_quantity, product_amount,  product_id) VALUES(2, '2024-01-05', 1, 0.0, 1);
INSERT INTO tb_debt(client_id, debt_date, product_quantity, product_amount,  product_id) VALUES(7, '2024-01-20', 6, 0.0, 2);
INSERT INTO tb_debt(client_id, debt_date, product_quantity, product_amount,  product_id) VALUES(3, '2024-02-02', 5, 0.0, 4);
INSERT INTO tb_debt(client_id, debt_date, product_quantity, product_amount,  product_id) VALUES(3, '2024-02-05', 2, 0.0, 6);
INSERT INTO tb_debt(client_id, debt_date, product_quantity, product_amount,  product_id) VALUES(8, '2024-02-13', 4, 0.0, 5);
INSERT INTO tb_debt(client_id, debt_date, product_quantity, product_amount,  product_id) VALUES(6, '2024-02-16', 2, 0.0, 8);
INSERT INTO tb_debt(client_id, debt_date, product_quantity, product_amount,  product_id) VALUES(4, '2024-02-16', 6, 0.0, 3);
INSERT INTO tb_debt(client_id, debt_date, product_quantity, product_amount,  product_id) VALUES(4, '2024-02-16', 2, 0.0, 9);
INSERT INTO tb_debt(client_id, debt_date, product_quantity, product_amount,  product_id) VALUES(4, '2024-03-07', 5, 0.0, 7);
INSERT INTO tb_debt(client_id, debt_date, product_quantity, product_amount,  product_id) VALUES(4, '2024-03-07', 4, 0.0, 2);
INSERT INTO tb_debt(client_id, debt_date, product_quantity, product_amount,  product_id) VALUES(5, '2024-02-05', 4, 0.0, 1);
INSERT INTO tb_debt(client_id, debt_date, product_quantity, product_amount,  product_id) VALUES(5, '2024-04-12', 6, 0.0, 7);
INSERT INTO tb_debt(client_id, debt_date, product_quantity, product_amount,  product_id) VALUES(5, '2024-04-12', 9, 0.0, 4);
INSERT INTO tb_debt(client_id, debt_date, product_quantity, product_amount,  product_id) VALUES(9, '2024-05-20', 3, 0.0, 1);
INSERT INTO tb_debt(client_id, debt_date, product_quantity, product_amount,  product_id) VALUES(10, '2024-05-30', 2, 0.0, 12);
INSERT INTO tb_debt(client_id, debt_date, product_quantity, product_amount,  product_id) VALUES(6, '2024-02-02', 2, 0.0, 2);
INSERT INTO tb_debt(client_id, debt_date, product_quantity, product_amount,  product_id) VALUES(6, '2024-02-16', 7, 0.0, 5);
INSERT INTO tb_debt(client_id, debt_date, product_quantity, product_amount,  product_id) VALUES(7, '2024-02-13', 3, 0.0, 10);
INSERT INTO tb_debt(client_id, debt_date, product_quantity, product_amount,  product_id) VALUES(7, '2024-01-20', 6, 0.0, 6);
INSERT INTO tb_debt(client_id, debt_date, product_quantity, product_amount,  product_id) VALUES(7, '2024-03-05', 1, 0.0, 8);
INSERT INTO tb_debt(client_id, debt_date, product_quantity, product_amount,  product_id) VALUES(7, '2024-04-30', 9, 0.0, 3);
INSERT INTO tb_debt(client_id, debt_date, product_quantity, product_amount,  product_id) VALUES(8, '2024-02-13', 1, 0.0, 4);
INSERT INTO tb_debt(client_id, debt_date, product_quantity, product_amount,  product_id) VALUES(8, '2024-02-13', 2, 0.0, 10);
INSERT INTO tb_debt(client_id, debt_date, product_quantity, product_amount,  product_id) VALUES(8, '2024-03-08', 4, 0.0, 6);
INSERT INTO tb_debt(client_id, debt_date, product_quantity, product_amount,  product_id) VALUES(8, '2024-04-30', 5, 0.0, 7);
INSERT INTO tb_debt(client_id, debt_date, product_quantity, product_amount,  product_id) VALUES(1, '2024-01-12', 1, 0.0, 11);
INSERT INTO tb_debt(client_id, debt_date, product_quantity, product_amount,  product_id) VALUES(1, '2024-02-22', 6, 0.0, 7);
INSERT INTO tb_debt(client_id, debt_date, product_quantity, product_amount,  product_id) VALUES(1, '2024-04-13', 8, 0.0, 4);
INSERT INTO tb_debt(client_id, debt_date, product_quantity, product_amount,  product_id) VALUES(1, '2024-04-13', 4, 0.0, 2);
INSERT INTO tb_debt(client_id, debt_date, product_quantity, product_amount,  product_id) VALUES(2, '2024-01-10', 6, 0.0, 1);
INSERT INTO tb_debt(client_id, debt_date, product_quantity, product_amount,  product_id) VALUES(2, '2024-01-20', 3, 0.0, 11);
INSERT INTO tb_debt(client_id, debt_date, product_quantity, product_amount,  product_id) VALUES(3, '2024-01-05', 5, 0.0, 9);
INSERT INTO tb_debt(client_id, debt_date, product_quantity, product_amount,  product_id) VALUES(3, '2024-02-05', 4, 0.0, 2);
INSERT INTO tb_debt(client_id, debt_date, product_quantity, product_amount,  product_id) VALUES(3, '2024-06-25', 3, 0.0, 3);
INSERT INTO tb_debt(client_id, debt_date, product_quantity, product_amount, product_id) VALUES (15, '2024-02-01', 2, 0.0, 12);
INSERT INTO tb_debt(client_id, debt_date, product_quantity, product_amount, product_id) VALUES (16, '2024-03-10', 1, 0.0, 13);
INSERT INTO tb_debt(client_id, debt_date, product_quantity, product_amount, product_id) VALUES (17, '2024-04-15', 3, 0.0, 14);
INSERT INTO tb_debt(client_id, debt_date, product_quantity, product_amount, product_id) VALUES (18, '2024-05-20', 1, 0.0, 15);
INSERT INTO tb_debt(client_id, debt_date, product_quantity, product_amount, product_id) VALUES (19, '2024-06-25', 4, 0.0, 16);
INSERT INTO tb_debt(client_id, debt_date, product_quantity, product_amount, product_id) VALUES (20, '2024-07-30', 2, 0.0, 17);
INSERT INTO tb_debt(client_id, debt_date, product_quantity, product_amount, product_id) VALUES (21, '2024-08-10', 3, 0.0, 18);
INSERT INTO tb_debt(client_id, debt_date, product_quantity, product_amount, product_id) VALUES (22, '2024-09-15', 1, 0.0, 19);
INSERT INTO tb_debt(client_id, debt_date, product_quantity, product_amount, product_id) VALUES (23, '2024-10-20', 2, 0.0, 20);
INSERT INTO tb_debt(client_id, debt_date, product_quantity, product_amount, product_id) VALUES (24, '2024-11-25', 3, 0.0, 21);
INSERT INTO tb_debt(client_id, debt_date, product_quantity, product_amount, product_id) VALUES (25, '2024-12-30', 2, 0.0, 22);
INSERT INTO tb_debt(client_id, debt_date, product_quantity, product_amount, product_id) VALUES (26, '2024-01-10', 1, 0.0, 12);
INSERT INTO tb_debt(client_id, debt_date, product_quantity, product_amount, product_id) VALUES (27, '2024-02-15', 3, 0.0, 13);
INSERT INTO tb_debt(client_id, debt_date, product_quantity, product_amount, product_id) VALUES (28, '2024-03-20', 2, 0.0, 14);
INSERT INTO tb_debt(client_id, debt_date, product_quantity, product_amount, product_id) VALUES (29, '2024-04-25', 4, 0.0, 15);
INSERT INTO tb_debt(client_id, debt_date, product_quantity, product_amount, product_id) VALUES (30, '2024-05-30', 3, 0.0, 16);



INSERT INTO tb_paid(client_id, product_id, payment_date, payment_type, product_quantity, product_amount) VALUES(5, 2, '2024-04-01', 'PIX', 2, 0.0);
INSERT INTO tb_paid(client_id, product_id, payment_date, payment_type, product_quantity, product_amount) VALUES(1, 4, '2024-04-04', 'Cartão de Crédito', 2, 0.0);
INSERT INTO tb_paid(client_id, product_id, payment_date, payment_type, product_quantity, product_amount) VALUES(1, 2, '2024-04-04', 'Cartão de Crédito', 1, 0.0);
INSERT INTO tb_paid(client_id, product_id, payment_date, payment_type, product_quantity, product_amount) VALUES(1, 8, '2024-04-04', 'Cartão de Crédito', 4, 0.0);
INSERT INTO tb_paid(client_id, product_id, payment_date, payment_type, product_quantity, product_amount) VALUES(1, 3, '2024-04-12', 'Cartão de Crédito', 2, 0.0);
INSERT INTO tb_paid(client_id, product_id, payment_date, payment_type, product_quantity, product_amount) VALUES(1, 6, '2024-04-12', 'Cartão de Crédito', 6, 0.0);
INSERT INTO tb_paid(client_id, product_id, payment_date, payment_type, product_quantity, product_amount) VALUES(2, 5, '2024-04-05', 'Dinheiro', 2, 0.0);
INSERT INTO tb_paid(client_id, product_id, payment_date, payment_type, product_quantity, product_amount) VALUES(7, 6, '2024-04-10', 'PIX', 2, 0.0);
INSERT INTO tb_paid(client_id, product_id, payment_date, payment_type, product_quantity, product_amount) VALUES(8, 3, '2024-04-12', 'Cartão de Crédito', 2, 0.0);
INSERT INTO tb_paid(client_id, product_id, payment_date, payment_type, product_quantity, product_amount) VALUES(6, 1, '2024-04-14', 'PIX', 2, 0.0);
INSERT INTO tb_paid(client_id, product_id, payment_date, payment_type, product_quantity, product_amount) VALUES(8, 7, '2024-04-10', 'PIX', 3, 0.0);
INSERT INTO tb_paid(client_id, product_id, payment_date, payment_type, product_quantity, product_amount) VALUES(4, 9, '2024-04-14', 'Dinheiro', 2, 0.0);
INSERT INTO tb_paid(client_id, product_id, payment_date, payment_type, product_quantity, product_amount) VALUES(3, 5, '2024-04-14', 'PIX', 2, 0.0);
INSERT INTO tb_paid(client_id, product_id, payment_date, payment_type, product_quantity, product_amount) VALUES(4, 2, '2024-04-10', 'PIX', 3, 0.0);
INSERT INTO tb_paid(client_id, product_id, payment_date, payment_type, product_quantity, product_amount) VALUES(5, 10, '2024-04-12', 'Cartão de Crédito', 4, 0.0);
INSERT INTO tb_paid(client_id, product_id, payment_date, payment_type, product_quantity, product_amount) VALUES(6, 11, '2024-04-14', 'Dinheiro', 2, 0.0);
INSERT INTO tb_paid(client_id, product_id, payment_date, payment_type, product_quantity, product_amount) VALUES(3, 12, '2024-04-01', 'PIX', 4, 0.0);
INSERT INTO tb_paid(client_id, product_id, payment_date, payment_type, product_quantity, product_amount) VALUES(6, 13, '2024-04-05', 'Dinheiro', 6, 0.0);
INSERT INTO tb_paid(client_id, product_id, payment_date, payment_type, product_quantity, product_amount) VALUES(7, 14, '2024-04-10', 'PIX', 2, 0.0);
INSERT INTO tb_paid(client_id, product_id, payment_date, payment_type, product_quantity, product_amount) VALUES(4, 15, '2024-04-12', 'Cartão de Crédito', 3, 0.0);
INSERT INTO tb_paid(client_id, product_id, payment_date, payment_type, product_quantity, product_amount) VALUES (9, 16, '2024-01-15', 'PIX', 1, 0.0);
INSERT INTO tb_paid(client_id, product_id, payment_date, payment_type, product_quantity, product_amount) VALUES (9, 17, '2024-02-20', 'Cartão de Crédito', 3, 0.0);
INSERT INTO tb_paid(client_id, product_id, payment_date, payment_type, product_quantity, product_amount) VALUES (10, 18, '2024-03-05', 'Débito', 2, 0.0);
INSERT INTO tb_paid(client_id, product_id, payment_date, payment_type, product_quantity, product_amount) VALUES (10, 19, '2024-04-10', 'PIX', 4, 0.0);
INSERT INTO tb_paid(client_id, product_id, payment_date, payment_type, product_quantity, product_amount) VALUES (10, 20, '2024-05-12', 'Dinheiro', 1, 0.0);
INSERT INTO tb_paid(client_id, product_id, payment_date, payment_type, product_quantity, product_amount) VALUES (11, 21, '2024-06-15', 'Pix', 2, 0.0);
INSERT INTO tb_paid(client_id, product_id, payment_date, payment_type, product_quantity, product_amount) VALUES (12, 22, '2024-07-18', 'Débito', 3, 0.0);
INSERT INTO tb_paid(client_id, product_id, payment_date, payment_type, product_quantity, product_amount) VALUES (13, 4, '2024-08-20', 'Cartão de Crédito', 1, 0.0);
INSERT INTO tb_paid(client_id, product_id, payment_date, payment_type, product_quantity, product_amount) VALUES (14, 5, '2024-09-22', 'Boleto', 2, 0.0);
INSERT INTO tb_paid(client_id, product_id, payment_date, payment_type, product_quantity, product_amount) VALUES (15, 7, '2024-10-24', 'Dinheiro', 1, 0.0);
INSERT INTO tb_paid(client_id, product_id, payment_date, payment_type, product_quantity, product_amount) VALUES (16, 4, '2024-11-26', 'Pix', 3, 0.0);
INSERT INTO tb_paid(client_id, product_id, payment_date, payment_type, product_quantity, product_amount) VALUES (17, 8, '2024-12-28', 'Débito', 2, 0.0);
INSERT INTO tb_paid(client_id, product_id, payment_date, payment_type, product_quantity, product_amount) VALUES (18, 3, '2025-01-01', 'Cartão de Crédito', 1, 0.0);
INSERT INTO tb_paid(client_id, product_id, payment_date, payment_type, product_quantity, product_amount) VALUES (19, 5, '2025-02-03', 'Boleto', 2, 0.0);
INSERT INTO tb_paid(client_id, product_id, payment_date, payment_type, product_quantity, product_amount) VALUES (20, 5, '2024-11-15', 'Dinheiro', 2, 0.0);
INSERT INTO tb_paid(client_id, product_id, payment_date, payment_type, product_quantity, product_amount) VALUES (20, 10, '2024-10-03', 'Pix', 2, 0.0);
INSERT INTO tb_paid(client_id, product_id, payment_date, payment_type, product_quantity, product_amount) VALUES (21, 6, '2024-12-10', 'Pix', 1, 0.0);
INSERT INTO tb_paid(client_id, product_id, payment_date, payment_type, product_quantity, product_amount) VALUES (22, 7, '2025-01-05', 'Débito', 3, 0.0);
INSERT INTO tb_paid(client_id, product_id, payment_date, payment_type, product_quantity, product_amount) VALUES (23, 8, '2024-02-20', 'Cartão de Crédito', 4, 0.0);
INSERT INTO tb_paid(client_id, product_id, payment_date, payment_type, product_quantity, product_amount) VALUES (24, 9, '2024-03-15', 'Boleto', 1, 0.0);
INSERT INTO tb_paid(client_id, product_id, payment_date, payment_type, product_quantity, product_amount) VALUES (25, 10, '2024-04-08', 'Dinheiro', 2, 0.0);
INSERT INTO tb_paid(client_id, product_id, payment_date, payment_type, product_quantity, product_amount) VALUES (26, 11, '2024-05-01', 'Pix', 3, 0.0);
INSERT INTO tb_paid(client_id, product_id, payment_date, payment_type, product_quantity, product_amount) VALUES (27, 12, '2024-06-14', 'Débito', 2, 0.0);
INSERT INTO tb_paid(client_id, product_id, payment_date, payment_type, product_quantity, product_amount) VALUES (28, 7, '2024-07-20', 'Cartão de Crédito', 1, 0.0);
INSERT INTO tb_paid(client_id, product_id, payment_date, payment_type, product_quantity, product_amount) VALUES (29, 8, '2024-08-05', 'Boleto', 4, 0.0);
INSERT INTO tb_paid(client_id, product_id, payment_date, payment_type, product_quantity, product_amount) VALUES (30, 9, '2024-09-12', 'Dinheiro', 3, 0.0);
